name: Ebuild Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v4
    - name: Kalles-Sources
      run:  sudo ebuild sys-kernel/kalles-sources/kalles-sources-*.ebuild clean test install
    - name: Kalles-dwl
      run:  sudo ebuild gui-wm/dwl/dwl-*.ebuild clean test install
