name: Kalles-Sources Ebuild Testing

on:
  push:
    paths:
      - sys-kernel/kalles-sources/**

jobs:
  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v4
    - name: Kalles-Sources
      run:  sudo ebuild sys-kernel/kalles-sources/kalles-sources-*.ebuild clean test install
